spring:
  datasource:
    url: jdbc:mysql://localhost:3308/lab_safety?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: lab
    password: lab
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration




app:
  jwt:
    secret: YjVhMmQyMzQ0YjQ4NGY5NTk5M2EwMjk0YjQ0ZGFkYTQxM2YzYTQ1M2IxM2Y3YTFkZGI4M2Q5ZmY2MDYxZg==
    expiration-ms: 3600000
